### ISSUE TITLE
Permission Required to Host Website

### ISSUE THREAD

**Issue by ajaygandecha** [comp426-2023-spring/a99#8]
Hello Professor @jdmar3! Sorry for this quick message, but in order to deploy our website, we need to grant Vercel access to our repository. I have requested for permission, but I think it is sent to the organization owner and not to the repository owners! We only requested access to our single repository, so I was hoping you would be able to approve this for us.

Thank you very much!

Team "BetterCat" + Ajay

**Comment by jdmar3** [comment]
Create a fork of your repository in one of your accounts and then you will have permissions control of that fork. You can then grant your other team members administrative access to that fork if you need or want to. You can always create pull requests from a production fork on one of your accounts back to the org repo as well. 

I have run into this before with organizations and the permissions required are too broad scope for me to allow since they necessarily extend to the entire org.

**Comment by ajaygandecha** [comment]
@jdmar3 thank you for the response! I was able to host it [live](https://unc-food-tracker.vercel.app/restaurants). Appreciate it!
